# This is a basic workflow to help you get started with Actions

name: Bump

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Install required PowerShell modules
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSIni -ErrorAction Stop
      
    - name: Bump
      run: pwsh -ExecutionPolicy ByPass -File bump.ps1
      timeout-minutes: 10

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump
